version: 2.1

executors:
  maven:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: /tmp/build

jobs:
  build:
    executor: maven
    steps:
      - checkout
      - restore_cache:
          key: confapi-plugin-{{ checksum "pom.xml" }}
      - run:
          name: Download Dependencies
          command: ./mvnw dependency:go-offline -U
      - run:
          name: Compile and Package
          command: ./mvnw package -DskipUnitTests
      - run:
          name: Copy Artifacts into separate Directory
          command: mkdir -p /tmp/artifacts && cp target/*.{jar,obr} /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
      - persist_to_workspace:
          root: /tmp/build
          paths:
            - .
      - save_cache:
          paths:
            - ~/.m2
          key: confapi-plugin-{{ checksum "pom.xml" }}
  unit-tests:
    executor: maven
    steps:
      - attach_workspace:
          at: /tmp/build
      - restore_cache:
          key: confapi-plugin-{{ checksum "pom.xml" }}
      - run:
          name: Run Unit Tests and analyze on SonarCloud
          command: ./mvnw test sonar:sonar
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          paths:
            - ~/.m2
          key: confapi-plugin-{{ checksum "pom.xml" }}
  integration-tests:
    executor: maven
    steps:
      - attach_workspace:
          at: /tmp/build
      - restore_cache:
          key: confapi-plugin-{{ checksum "pom.xml" }}
      - run:
          name: Run Integration Tests
          command: ./mvnw integration-test -DskipUnitTests
      - save_cache:
          paths:
            - ~/.m2
          key: confapi-plugin-{{ checksum "pom.xml" }}
  deploy:
    executor: maven
    steps:
      - attach_workspace:
          at: /tmp/build
      - restore_cache:
          key: confapi-plugin-{{ checksum "pom.xml" }}
      - run:
          name: Decrypt Signing Key
          command: openssl aes-256-cbc -S ${SIGN_ASC_SALT} -K ${SIGN_ASC_KEY} -iv ${SIGN_ASC_IV} -in .circleci/sign.asc.enc -out .circleci/sign.asc -d
      - run:
          name: Import Signing Key
          command: gpg --no-tty --batch --import .circleci/sign.asc
      - run:
          name: Deploy to Maven Central
          command: export GPG_TTY=$(tty) && ./mvnw -s .circleci/settings.xml -DskipTests deploy
      - save_cache:
          paths:
            - ~/.m2
          key: confapi-plugin-{{ checksum "pom.xml" }}
  apcc:
    executor: maven
    steps:
      - attach_workspace:
          at: /tmp/build
      - restore_cache:
          key: confapi-plugin-{{ checksum "pom.xml" }}
      - run:
          name: Download APCC
          command: ./mvnw dependency:get -DgroupId=de.aservo -DartifactId=atlassian-plugin-compatibility-check -Dversion=0.0.2
      - run:
          name: Copy APCC to current Directory
          command: ./mvnw dependency:copy -Dartifact=de.aservo:atlassian-plugin-compatibility-check:0.0.2 -DoutputDirectory=.
      - run:
          name: Run APCC
          command: java -jar atlassian-plugin-compatibility-check-0.0.2.jar "jira.version"
      - save_cache:
          paths:
            - ~/.m2
          key: confapi-plugin-{{ checksum "pom.xml" }}

workflows:
  main:
    jobs:
      - build
      - unit-tests:
          requires:
            - build
          context: global
      - integration-tests:
          requires:
            - build
      - deploy:
          requires:
            - unit-tests
            - integration-tests
          filters:
            branches:
              only: master
          context: deploy-maven
      - apcc:
          requires:
            - deploy
          filters:
            branches:
              only: master
